# hpc-common/tasks/main.yml
---

- name: Install common HPC software (Debian/Ubuntu)
  package:
    name:
      - build-essential
      - gfortran
      - libatlas-base-dev
      - libhdf5-dev
      - libhdf5-openmpi-dev
      - liblapack-dev
      - libnetcdf-dev
      - libopenblas-dev
      - libopenmpi-dev
      - sqlite3
    state: '{{ pkg_install_state }}'
  when: is_debian_compatible


- name: Install common HPC software (RHEL/CentOS)
  package:
    name:
      - gcc-c++
      - gcc-gfortran
      - make
      - openmpi-devel
      - openmpi3-devel
      - libipm-openmpi
      - libipm-openmpi3
    state: '{{ pkg_install_state }}'
  when: is_rhel7_compatible


- name: Install common HPC software (RHEL/CentOS 6.x)
  package:
    name:
      - atlas-devel
      - gcc-c++
      - gcc-gfortran
      - hdf5
      - hdf5-openmpi
      - hdf5-openmpi-devel
      - make
      - netcdf-devel
      - openblas-devel
      - openmpi-1.8-devel
      - scalapack-openmpi
      - scalapack-openmpi-devel
    state: '{{ pkg_install_state }}'
  when: is_rhel6_compatible
